[project]
authors = ["a.gostynskiglina <a.gostynskiglina@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "bioinf_strukt_l2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.0,<3.13.0"
numpy = ">=2.1.3,<3"
biopython = ">=1.84,<2"
